name: compile
on: [push]
jobs:
  compile:
    runs-on: ubuntu-latest
    env:
      # NOTE: this private key is from the hardhat node and is known - so no leaks here
      PRIVATE_KEY: "ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
      API_URL: https://example.org/
      API_KEY: "1234"
      NETWORK: not_used
      ETHERSCAN_API_KEY: "1234"
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: "yarn"
    - run: yarn install
    - run: npx hardhat run &
    - run: npx hardhat compile --network localhost
    - uses: actions/upload-artifact@v3
      with:
        name: contracts
        path: ./artifacts/contracts/**/*.json